# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/car.xdc

# Block Designs: bd/ip_car/ip_car.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car || ORIG_REF_NAME==ip_car}]

# IP: bd/ip_car/ip/ip_car_motor_1_0/ip_car_motor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car_motor_1_0 || ORIG_REF_NAME==ip_car_motor_1_0}]

# IP: bd/ip_car/ip/ip_car_clkdiv_1_0/ip_car_clkdiv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car_clkdiv_1_0 || ORIG_REF_NAME==ip_car_clkdiv_1_0}]

# IP: bd/ip_car/ip/ip_car_RF_r_1_0/ip_car_RF_r_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car_RF_r_1_0 || ORIG_REF_NAME==ip_car_RF_r_1_0}]

# IP: bd/ip_car/ip/ip_car_uart_1_0/ip_car_uart_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car_uart_1_0 || ORIG_REF_NAME==ip_car_uart_1_0}]

# IP: bd/ip_car/ip/ip_car_centre_1_0/ip_car_centre_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ip_car_centre_1_0 || ORIG_REF_NAME==ip_car_centre_1_0}]
