# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
create_project -in_memory -part xc7z020clg484-1
set_property board em.avnet.com:zynq:zed:d [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog C:/Users/Administrator/Desktop/ZedBoard/Prj/motorIP/motor/motor.srcs/sources_1/new/motor.v
set_property webtalk.parent_dir C:/Users/Administrator/Desktop/ZedBoard/Prj/motorIP/motor/motor.data/wt [current_project]
set_property parent.project_dir C:/Users/Administrator/Desktop/ZedBoard/Prj/motorIP/motor [current_project]
synth_design -top motor -part xc7z020clg484-1
write_checkpoint motor.dcp
report_utilization -file motor_utilization_synth.rpt -pb motor_utilization_synth.pb
